### ISSUE TITLE
Artifact pb with breakages

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/CTActions#11]
@ocots @PierreMartinon referring to this issue https://github.com/control-toolbox/CTDirect.jl/pull/348#issuecomment-2653085655

@amontoison did you run into the same pb with artifacts? the case being, can you please point towards a fix?

**Comment by ocots** [comment]
Here you have an example which works: https://github.com/control-toolbox/CTDirect.jl/issues/345#issuecomment-2585051342

**Comment by jbcaillau** [comment]
thanks @ocots 

> Here you have an example which works: [control-toolbox/CTDirect.jl#345 (comment)](https://github.com/control-toolbox/CTDirect.jl/issues/345#issuecomment-2585051342)

@amontoison it points towards what you did to deal with this issue: any comment welcome!

@srcansiz @j-l-s guys we need some help for this artifact update 🙏🏽

See also: https://securitylab.github.com/resources/github-actions-new-patterns-and-mitigations

**Comment by amontoison** [comment]
@jbcaillau Sorry for not answering earlier.
It was a busy week...
I think we just need to update the version of a GHA to fix the issue:
 https://github.com/amontoison/Krylov.jl/pull/4

**Comment by srcansiz** [comment]
Hi @jbcaillau,
I'm on leave. I'll be back the week of February 24. I'll check this issue when I get back.

**Comment by jbcaillau** [comment]
Thank you @srcansiz. we can live without non-breakage tests 🥲

**Comment by jbcaillau** [comment]
@PierreMartinon @ocots @srcansiz 

- should now be solved by https://github.com/control-toolbox/CTDirect.jl/issues/345
- [ ] delete all `commentPR.yml` from all repos
- [ ] delete `commentpr.yml` in CTActions

**Comment by srcansiz** [comment]
Hi @jbcaillau,

Is there anything has to be done for this issue or it is solved? Are the following actions still required? 


> delete all commentPR.yml from all repos
> delete commentpr.yml in CTActions
> same for applications breakage

**Comment by jbcaillau** [comment]
hi @srcansiz thanks for the heads up. i would answer yes for the three mentioned points. @ocots @PierreMartinon can you please confirm?

**Comment by ocots** [comment]
The file [breakage-application.yml](https://github.com/control-toolbox/CTActions/blob/main/.github/workflows/breakage-application.yml) must be updated following what @PierreMartinon has done with [breakage.yml](https://github.com/control-toolbox/CTActions/blob/main/.github/workflows/breakage.yml). Actually, updating the artifact version leads to use differently the comment process. We have removed the files about commenting in a PR because now it is directly inside the breakage action:

https://github.com/control-toolbox/CTActions/blob/79e938e591e4a2a1e2fd650b8f4c934c80d0c176/.github/workflows/breakage.yml#L97

**Comment by ocots** [comment]
I have fixed the breakage action:

https://github.com/control-toolbox/CTActions/blob/a771f7bb6f69e9e03062a62dd3bf3941992b16be/.github/workflows/breakage.yml#L97

Here is an example:

```yml
# Ref: https://securitylab.github.com/research/github-actions-preventing-pwn-requests
name: Breakage

# read-only repo token
# no access to secrets
on:
  pull_request:

jobs:
  break:
    strategy:
      fail-fast: false
      matrix:
        pkgname: [CTDirect, CTFlows, OptimalControl]
        pkgversion: [latest, stable]
        include:
          - pkgpath: control-toolbox
    uses: control-toolbox/CTActions/.github/workflows/breakage.yml@main
    with:
      pkgname: ${{ matrix.pkgname }}
      pkgpath: ${{ matrix.pkgpath }}
      pkgversion: ${{ matrix.pkgversion }}
```
