### ISSUE TITLE
Code coverage

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/CTActions#12]
@j-l-s @srcansiz looks like we have a more general issue with code coverage CI:
- not working in CTParser.jl https://github.com/control-toolbox/CTParser.jl/issues/8
- not working in the other packages either

Any clue?

**Comment by srcansiz** [comment]
Hi @jbcaillau,

It seems that codecov for `CTParser` is not public or not existing at all. See https://app.codecov.io/gh/control-toolbox/CTParser.jl , I would recommend to check it from codecov using an authorized account.

**Comment by jbcaillau** [comment]
hi @srcansiz having a look at it (indeed, i did not perform any action / add any token...) for this repo. but actually, the problem is the same with other repos of the control-toobox org for which codecov used to work but has not been updated for several months 😬

@ocots may be you can precise on that?

**Comment by srcansiz** [comment]
I suspect that it is because every repository created in `codecov` has different token, and I am not sure if `secrect.CODECOV_TOKEN` in `CTActions/.github/workflows/coverage.yml` refers to correct secret in the repository that it is executed/called/used. I added  a explicit secret variable called `codecov-token` to this workflow that every repository can pass its assigned codecov token (see https://github.com/control-toolbox/CTActions/blob/main/.github/workflows/coverage.yml). Therefore, the usage in every repository has to be updated as follow: 

```yml
jobs:
  test:
    uses: control-toolbox/CTActions/.github/workflows/coverage.yml@main 
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
```

The changes have been pushed. @ocots can you please update one of the test CI execution to see if it solves the problem. Otherwise, I can revert my changes.

**Comment by ocots** [comment]
If I write this:

```yml
# [.github/workflows/coverage.yml]
name: coverage
on:
  push:
    branches:
      - main
    tags: '*'
jobs:
  test:
    uses: control-toolbox/CTActions/.github/workflows/coverage.yml@main
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
```

I get in VSCode the error message:

```
Invalid secret, codecov-token is not defined in the referenced workflow.
```
